# Generated by Django 4.1.3 on 2022-11-08 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15, verbose_name='defina el estado')),
                ('descripcion', models.CharField(max_length=15, verbose_name='de una breve descripción del estado')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Placa ')),
                ('evaluacion', models.CharField(choices=[('Malo', 'malo'), ('Regular', 'regular'), ('Bueno', 'bueno'), ('Excelente', 'excelente')], max_length=50, verbose_name='Tipo de vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar_llegada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100, verbose_name='Lugar de la ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar_salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100, verbose_name='Lugar de la ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='LugarNacimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Lugar de nacimiento')),
                ('departamento', models.CharField(max_length=100, verbose_name='Estado/Departamento')),
                ('pais', models.CharField(max_length=100, null=True, verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=10, null=True, verbose_name='marca')),
                ('tipo_vehiculo', models.CharField(choices=[('Bicicleta', 'Bicicleta'), ('Moto', 'Moto'), ('Sedan', 'Sedan'), ('Camioneta', 'Camioneta'), ('Camión', 'Camión')], max_length=50, verbose_name='Tipo de vehiculo')),
                ('anio', models.DateField(verbose_name='escriba la fecha de compra del vehículo')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa ')),
                ('foto', models.ImageField(null=True, upload_to='vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=100, verbose_name='Ruta')),
                ('desde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lugar_salida', verbose_name='lugar referencial de salida')),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lugar_llegada', verbose_name='lugar referencial de llegada')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ruta', verbose_name='ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='¿asigne un t´tulo de referencia a la encomienda?')),
                ('nombre_envia', models.CharField(max_length=15, verbose_name='¿Quién envía?')),
                ('telefono_envía', models.CharField(max_length=15, verbose_name='teléfono de quien envía')),
                ('dirección_salida', models.CharField(max_length=100, verbose_name='Dirección exacta de salida')),
                ('punto_referencia_salida', models.CharField(max_length=100, verbose_name='proporcione un punto de referencia de salida')),
                ('nombre_recibe', models.CharField(max_length=15, verbose_name='¿Quién envía?')),
                ('telefono_recibe', models.CharField(max_length=15, verbose_name='teléfono de quien envía')),
                ('dirección_llegada', models.CharField(max_length=100, verbose_name='Dirección exacta de llegada')),
                ('punto_referencia_llegada', models.CharField(max_length=100, verbose_name='proporcione un punto de referencia de  llegada')),
                ('evaluacion', models.CharField(choices=[('Malo', 'malo'), ('Regular', 'regular'), ('Bueno', 'bueno'), ('Excelente', 'excelente')], max_length=50, verbose_name='Tipo de vehiculo')),
                ('descripcion_evaluacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Placa ')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estado', verbose_name='estado de la encomienda')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ruta', verbose_name='ruta')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoDetalle',
            fields=[
                ('nombre', models.CharField(max_length=100, verbose_name='Número de documento de identidad')),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.vehiculo')),
                ('numero_identidad', models.CharField(max_length=100, verbose_name='Número de documento de identidad')),
                ('telefono', models.CharField(max_length=50, null=True, verbose_name='Teléfono local')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('estado_civil', models.CharField(choices=[('SO', 'Soltero'), ('CA', 'Casado'), ('UH', 'Union de hecho')], default='CA', max_length=2, verbose_name='Estado Civil')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('estado_trabajador', models.CharField(choices=[('TA', 'Trabajando'), ('DE', 'Descanso')], default='DE', max_length=2, verbose_name='Estado del conductor')),
                ('ciudad_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lugarnacimiento', verbose_name='Lugar de nacimiento')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
