# Generated by Django 4.1.3 on 2022-11-08 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehiculoDetalle',
            new_name='Conductor',
        ),
        migrations.AddField(
            model_name='encomienda',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.conductor', verbose_name='elija el conductor'),
        ),
    ]
