# Generated by Django 4.1.3 on 2022-11-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_vehiculodetalle_conductor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escriba peso aproximado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=10, null=True, verbose_name='Escriba peso aproximado')),
                ('descripción', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escriba peso aproximado')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajaConNosotro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Volumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.CharField(blank=True, max_length=10, null=True, verbose_name='Escriba peso aproximado')),
                ('alto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Escriba peso aproximado')),
                ('largo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Escriba peso aproximado')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='foto',
        ),
        migrations.AddField(
            model_name='conductor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='foto_vehiculo',
            field=models.ImageField(blank=True, null=True, upload_to='foto_vehiculo'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='celular',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono local'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='comentario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='evaluación '),
        ),
        migrations.AlterField(
            model_name='precio',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ruta', verbose_name='ruta'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='desde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lugar_salida', verbose_name='lugar referencial de salida'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='hasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lugar_llegada', verbose_name='lugar referencial de llegada'),
        ),
        migrations.AddField(
            model_name='precio',
            name='peso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.peso', verbose_name='ruta'),
        ),
        migrations.AddField(
            model_name='precio',
            name='tipo_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipomaterial', verbose_name='ruta'),
        ),
        migrations.AddField(
            model_name='precio',
            name='volumen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volumen', verbose_name='ruta'),
        ),
    ]
