# Generated by Django 4.1.3 on 2022-11-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_peso_tipomaterial_trabajaconnosotro_volumen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.conductor', verbose_name='conductor'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del conductor'),
        ),
    ]
