# Generated by Django 4.1.3 on 2022-11-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_conductor_colicionador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='evaluacion',
            field=models.CharField(blank=True, choices=[('Malo', 'malo'), ('Regular', 'regular'), ('Bueno', 'bueno'), ('Excelente', 'excelente')], max_length=50, null=True, verbose_name='evalue al conductor'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='nombre_recibe',
            field=models.CharField(max_length=15, verbose_name='¿Quién recibe?'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='telefono_recibe',
            field=models.CharField(max_length=15, verbose_name='teléfono de quien recibe'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='peso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.peso', verbose_name='peso'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='tipo_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipomaterial', verbose_name='tipo de materiales'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='volumen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volumen', verbose_name='volumen'),
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='descripción',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion del material'),
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='nombre',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='nombre del material'),
        ),
        migrations.AlterField(
            model_name='volumen',
            name='alto',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='alto'),
        ),
        migrations.AlterField(
            model_name='volumen',
            name='largo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='largo'),
        ),
        migrations.AlterField(
            model_name='volumen',
            name='volumen',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Escriba el volumen'),
        ),
    ]
