# Generated by Django 4.1.3 on 2022-11-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_conductor_colicionador'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='fecha_entrega',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de encargo'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='descripcion_evaluacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='descrpción de evaluación'),
        ),
    ]
