# Generated by Django 4.1.3 on 2022-11-21 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_encomienda_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del conductor'),
        ),
    ]
