# Generated by Django 4.1.3 on 2022-11-21 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_alter_encomienda_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encomienda',
            old_name='dirección_salida',
            new_name='direccion_salida',
        ),
        migrations.RenameField(
            model_name='encomienda',
            old_name='telefono_envía',
            new_name='telefono_envia',
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='mi usuario'),
        ),
    ]
