# Generated by Django 4.1.3 on 2022-11-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_dirección_salida_encomienda_direccion_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='numero_usuario',
            field=models.PositiveIntegerField(null=True, verbose_name='escriba su numero de usuario'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='¿asigne un título de referencia a la encomienda?'),
        ),
    ]
