# Generated by Django 4.1.3 on 2022-11-22 13:51

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_encomienda_numero_usuario_alter_encomienda_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='numero_usuario',
            field=models.PositiveIntegerField(null=True, validators=[app.models.validarUsuario], verbose_name='escriba su numero de usuario'),
        ),
    ]
