# Generated by Django 4.1.3 on 2022-11-22 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_encomienda_numero_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estado', verbose_name='estado de la encomienda'),
        ),
    ]
